<?php
/**
 * @author  aazztech
 * @since   1.0
 * @version 1.0
 */

\CSF::createSection(
	'findbiz',
	array(
		'title'  => esc_html__( 'Typography', 'findbiz-core' ),
		'icon'   => 'fas fa-font',
		'fields' => array(
			array(
				'id'              => 'typo_body',
				'type'            => 'typography',
				'title'           => esc_html__( 'Body', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '400',
					'font-size'      => '16',
					'line-height'    => '28',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'id'              => 'typo_h1',
				'type'            => 'typography',
				'title'           => esc_html__( 'Header h1', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '600',
					'font-size'      => '32',
					'line-height'    => '38',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'id'              => 'typo_h2',
				'type'            => 'typography',
				'title'           => esc_html__( 'Header h2', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '600',
					'font-size'      => '28',
					'line-height'    => '32',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'id'              => 'typo_h3',
				'type'            => 'typography',
				'title'           => esc_html__( 'Header h3', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '600',
					'font-size'      => '22',
					'line-height'    => '28',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'id'              => 'typo_h4',
				'type'            => 'typography',
				'title'           => esc_html__( 'Header h4', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '600',
					'font-size'      => '20',
					'line-height'    => '26',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'id'              => 'typo_h5',
				'type'            => 'typography',
				'title'           => esc_html__( 'Header h5', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '600',
					'font-size'      => '18',
					'line-height'    => '24',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'id'              => 'typo_h6',
				'type'            => 'typography',
				'title'           => esc_html__( 'Header h6', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'google'         => true,
					'font-family'    => 'Inter',
					'font-weight'    => '600',
					'font-size'      => '15',
					'line-height'    => '20',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'type'  => 'heading',
				'title' => esc_html__( 'Main Menu Items', 'findbiz-core' ),
			),
			array(
				'id'              => 'menu_typo',
				'type'            => 'typography',
				'title'           => esc_html__( 'Menu Font', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '400',
					'font-size'      => '16',
					'line-height'    => '26',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'type'  => 'heading',
				'title' => esc_html__( 'Sub Menu Items', 'findbiz-core' ),
			),
			array(
				'id'              => 'submenu_typo',
				'type'            => 'typography',
				'title'           => esc_html__( 'Submenu Font', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'font-family'    => 'Inter',
					'font-weight'    => '400',
					'font-size'      => '14',
					'line-height'    => '26',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
			array(
				'type'  => 'heading',
				'title' => esc_html__( 'Mobile Menu', 'findbiz-core' ),
			),
			array(
				'id'              => 'resmenu_typo',
				'type'            => 'typography',
				'title'           => esc_html__( 'Mobile Menu Font', 'findbiz-core' ),
				'text_align'      => false,
				'letter_spacing'  => false,
				'color'           => false,
				'word_spacing'    => false,
				'text_decoration' => false,
				'default'         => array(
					'google'         => true,
					'font-family'    => 'Inter',
					'font-weight'    => '400',
					'font-size'      => '14',
					'line-height'    => '21',
					'subset'         => 'latin-ext',
					'text-transform' => 'none',
				),
			),
		),
	)
);
